Refactor Authentication Routes and User RUD  and password routes
Sourav59580/question-management-service pull request #1
Opened 2024-12-16 12:29 UTC by Monika-dhiman

2024-12-17 05:33 UTC, Sourav59580 requested changes

2024-12-17 05:33 UTC, Sourav59580 commented on features/authentication/authentication.services.js
> +        !fullName ||
validate through joi

2024-12-17 10:51 UTC, Monika-dhiman commented on features/authentication/authentication.controller.js
> +  async createUser(req, res) {
done

2024-12-18 05:12 UTC, Sourav59580 requested changes

2024-12-18 05:20 UTC, Monika-dhiman commented on features/authentication/authentication.routes.js
> +router.get("/:user_id/send-otp", authenticationController.sendOTP);
Done

2024-12-18 05:21 UTC, Monika-dhiman commented on features/users/users.controller.js
> +      if (!users) {
Refactored

2024-12-18 10:47 UTC, Uttam1128 requested changes

2024-12-18 10:47 UTC, Uttam1128 commented on features/users/users.routes.js
> +router.get("/:user_id", usersController.getUserById);
Use camelCasing for keys

2024-12-18 10:47 UTC, Uttam1128 commented on features/users/users.routes.js
> +router.patch("/:user_id/reset-password", usersController.resetUserPassword);
maybe we can utilize reset password and set new password at single place

2024-12-18 10:47 UTC, Uttam1128 commented on features/users/users.services.js
> +      password: generatePassword(),
pass this function to model as default value

2024-12-18 10:47 UTC, Uttam1128 commented on features/users/users.services.js
> +    if (!user) {
don't need this check it will either throw error or create a user

2024-12-18 10:47 UTC, Uttam1128 commented on features/users/users.services.js
> +    if (!mail) {
think of a way to resend a mail if it somehow fails without using rabbitmq

2024-12-18 10:47 UTC, Uttam1128 commented on features/users/user-validate.schema.js
> +  role: Joi.string().required(),
it is enum

2024-12-18 10:47 UTC, Uttam1128 commented on features/users/users.services.js
> +      throw new Error(`Validation error: ${error.details[0].message}`);
why show only 0th error message

2024-12-18 10:47 UTC, Uttam1128 commented on domain/user/user-entity.js
> +  return bcrypt.hash(password, salt);
check if you can use 'this' key here then you wont have to use different variable and logic to update password

2024-12-18 10:47 UTC, Uttam1128 commented on features/users/users.services.js
> +      password: encryptedPassword,
check discussion on userschema and try to send whole user payload inside

2024-12-18 10:47 UTC, Uttam1128 commented on domain/user/user-entity.js
> +  return bcrypt.hash(password, salt);
If 'this' work bind password data updation here

2024-12-18 10:47 UTC, Uttam1128 commented on infrastructure/utils/send-otp.js
> +const to = "918950523578";
use env for these as well

2024-12-18 10:47 UTC, Uttam1128 commented on infrastructure/utils/generate-password.js
> +exports.generatePassword = (length = 12) => {
should be near user Schema

2024-12-18 10:47 UTC, Uttam1128 commented on infrastructure/repositories/verification-token/verification-token.repository.js
> +    return this.findOne({ user_id: id }, projection, options);
why use $eq at one place and not other

2024-12-18 10:47 UTC, Uttam1128 commented on infrastructure/repositories/users/users.repository.js
> +  async findUserById(id, projection = {}, options = {}) {
Make a single find which search based on criteria whatever provided

2024-12-18 10:47 UTC, Uttam1128 commented on infrastructure/mailer/user-created-mail.js
> +export const sendMail  = async (email, password) => {
make this a generic mailing function and make a userRegistrationMail function to handle specific task

2024-12-18 10:47 UTC, Uttam1128 commented on features/authentication/authentication.services.js
> +        throw new Error("Email and password are required");
we cannot define what type of error is this by using just error? try using modules provided by kevin or any other convenient way

2024-12-18 10:47 UTC, Uttam1128 commented on features/authentication/authentication.services.js
> +          route: "/reset-password",
it would not be a 200 response. look at other response as well while setting response status.

2024-12-18 10:47 UTC, Uttam1128 commented on features/users/users.controller.js
> +      if (!user) return res.status(400).json("User not found");
well wouldn't it be 404? but on other hand we dont have a proper way to deal with status code here in controller implement one.

2024-12-18 10:47 UTC, Uttam1128 commented on features/users/users.controller.js
> +      console.error("Error in user controller", error);
should tell here during what the error has occured. it is wrong at all places

2024-12-18 10:47 UTC, Uttam1128 commented on infrastructure/mailer/user-created-mail.js
> +    console.log(error);
we wont be able to know is we got an error is that OK

2024-12-18 11:04 UTC, Sourav59580 commented on features/users/users.services.js
> +      password: generatePassword(),
don't do this

2024-12-18 13:03 UTC, Monika-dhiman commented on features/users/users.services.js
> +    if (!user) {
resolved

2024-12-18 13:03 UTC, Monika-dhiman commented on features/users/users.routes.js
> +router.get("/:user_id", usersController.getUserById);
resolved

2024-12-18 13:03 UTC, Monika-dhiman commented on features/authentication/authentication.controller.js
> +    const { user_id } = req.params;
resolved

2024-12-18 13:09 UTC, Monika-dhiman commented on infrastructure/utils/send-otp.js
> +const to = "918950523578";
This code is removed as this was unused code

2024-12-18 13:37 UTC, Monika-dhiman commented on features/users/users.services.js
> +      throw new Error(`Validation error: ${error.details[0].message}`);
- It is a common practice to show the first validation error to guide the user to fix one issue at a time. Users can fix errors one by one. Once the first error is fixed, the next validation error (if any) will be shown.
- But I have fixed it, and now it will show all the validation error messages into a single string, separated by commas as the **_error.details_** array is mapped to extract all error messages.

2024-12-19 04:30 UTC, Monika-dhiman commented on infrastructure/repositories/verification-token/verification-token.repository.js
> +    return this.findOne({ user_id: id }, projection, options);
Done

2024-12-19 04:38 UTC, Monika-dhiman commented on infrastructure/repositories/users/users.repository.js
> +  async findUserById(id, projection = {}, options = {}) {
Done

2024-12-19 04:52 UTC, Monika-dhiman commented on features/users/users.controller.js
> +      if (!user) return res.status(400).json("User not found");
Done

2024-12-19 04:58 UTC, Monika-dhiman commented on features/users/users.routes.js
> +router.patch("/:user_id/reset-password", usersController.resetUserPassword);
There is a difference in both routes. In the `/reset-password` route, the old password is required; in the `/set-new-password` route, it isn't.

2024-12-19 05:29 UTC, Monika-dhiman commented on features/authentication/authentication.services.js
> +        throw new Error("Email and password are required");
As we discussed, feature error handling has not been implemented yet. We will handle all these error in the feature error handling part.

2024-12-19 05:35 UTC, Monika-dhiman commented on features/authentication/authentication.services.js
> +          route: "/reset-password",
Can you explain me why it would not be 200 response.

2024-12-19 05:35 UTC, Monika-dhiman commented on features/users/users.controller.js
> +      console.error("Error in user controller", error);
As we discussed, feature error handling has not been implemented yet. We will handle all these errors in the feature error handling part.

2024-12-19 05:35 UTC, Monika-dhiman commented on infrastructure/mailer/user-created-mail.js
> +    console.log(error);
As we discussed, feature error handling has not been implemented yet. We will handle all these errors in the feature error handling part.

2024-12-19 07:25 UTC, merged